### ISSUE TITLE
ubuntu18.04LTS+宝塔面板，怎么部署 itranswarp

### ISSUE THREAD

**Issue by guoqiang5277** [michaelliao/itranswarp#11]
机器是：ubuntu18.04LTS，安装了宝塔面板对网站统一管理。
环境：通过宝塔面板配置的php7.3+mysql5.7+ngix1.6+Redis5+memcached1.5.7+nodejs8.10+openjdk11等。

/www/wwwroot/itranswarp/存放代码的位置。

通过命令
$ mysql -u root -p < release/ddl.sql
$ mysql -u root -p it < release/init.sql
成功创建数据库，并导入测试数据。

编译的时候碰到问题了：
1、存放代码的地方，所有者需要是www
-rwxr-xr-x 1 www  www    322 Nov  1 14:31 build.sh*
-rw-r--r-- 1 www  www   6610 Nov  1 14:31 checkstyle.xml
-rw-r--r-- 1 www  www  11357 Nov  1 14:31 LICENSE
但是编译的时候，又是用ubuntu的默认账号编译的。
两个所有者不一样，可能无法执行文件和编译。
我不知道应该怎么去编译。
2、看配置run的时候，是需要执行以下命令：
java -jar itranswarp.jar
我不知道应该怎么去运行。
3、部署
$ ansible/deploy.py --profile <env>
这个会自动部署一些软件，但是我现在的都已经通过宝塔面板部署完成了。
在宝塔的环境里面，配置其他的网站，我只需要吧php或者其他配置上传到/www/wwwroot/webname/ 到这个文件夹，然后就可以打开网页并使用了。
但是在 itranswarp我不知道应该怎么去使用他。
4、在ubuntu服务器，需要通过宝塔面板去管理里面的一些环境软件，还有几个web网站，所以我需要使用这样的环境。

**Comment by DeppWang** [comment]
使用 Docker，运行 `docker-compose up` 即可

安装 [Docker](https://docs.docker.com/install/linux/docker-ce/centos/)

安装 [Docker-Compose](https://docs.docker.com/compose/install/#install-compose)

启动项目
```shell
$ cd docker
$ cp .env.example .env # 修改服务器（计算机） hosts，相当于 DNS
$ vim .env # 修改为公网（本地） ip
$ docker-compose up 
```

**Comment by michaelliao** [comment]
参考README，用Ansible部署
