### ISSUE TITLE
请问登录的账号和口令是什么

### ISSUE THREAD

**Issue by cxinping** [michaelliao/itranswarp#17]
请问登录的账号和口令是什么？ 在sql文件里没有找到。

**Comment by xudeming** [comment]
账号在user表，密码在local_auths表。local_auths保存了salt和密文。
页面表单提交的参数为 email=邮箱, passwd=hmacSha256( 明文密码 , 邮箱)
后台验证时将 password加盐，再执行hmacSha256，得到的值和local_auths表密文匹配。
------
举例
String email = "admin@itranswarp.com";
String pwd = "123456";
String adminSalt = "e43c4c3d60e8646783a908538fda9b5cd6beb89f0aa7660b171f39d428a2dfe5";
String temp = HashUtil.hmacSha256( pwd,email);
String password = HashUtil.hmacSha256(temp, adminSalt);
// password=afd80550a4479ea7d4432e85c5c19f95d5339bd30ebdcf6313d3a4754e051164
这个password就是local_auths表中admin@itranswarp.com的密文。
