### ISSUE TITLE
使用weibo认证登录后无法正常跳转

### ISSUE THREAD

**Issue by theten52** [michaelliao/itranswarp#18]
登录后无法跳转回主页，刷新后显示已登录
<img width="1792" alt="截屏2019-12-18下午8 51 14" src="https://user-images.githubusercontent.com/19972299/71089220-52dd2300-21db-11ea-9841-fbfd9ed51ea5.png">

**Comment by theten52** [comment]
出现Whitelabel Page Error页面

**Comment by michaelliao** [comment]
fixed [#e60aa0d16d060f776953d4d02518ebc769285e96](https://github.com/michaelliao/itranswarp/commit/e60aa0d16d060f776953d4d02518ebc769285e96)
