### ISSUE TITLE
给小白出个部署的文档可好

### ISSUE THREAD

**Issue by sgseo** [michaelliao/itranswarp#23]
给小白出个部署的文档可好

**Comment by DeppWang** [comment]
使用 Docker，运行 `docker-compose up` 即可

安装 [Docker](https://docs.docker.com/install/linux/docker-ce/centos/)

安装 [Docker-Compose](https://docs.docker.com/compose/install/#install-compose)

启动项目

```shell
$ cd docker
$ cp .env.example .env # 修改服务器（计算机） hosts，相当于 DNS
$ vim .env # 修改为公网（本地） ip
$ docker-compose up 
```

**Comment by sgseo** [comment]
不需要使用docker呢？vps上有的不好使用docker

**Comment by DeppWang** [comment]
使用 docker 更简单，直接安装环境容易出错

**Comment by sgseo** [comment]
有一键部署的脚本就更好了 好像这里有一个python写的部署脚本 但是就是不知道怎么使用

**Comment by DeppWang** [comment]
你安装 docker 了，改一下 ip。直接一个命令（`docker-compose up`）就搞定了。这是最简单的方式了

**Comment by michaelliao** [comment]
README就是部署文档，Ansible一键部署
