### ISSUE TITLE
部署记录：https://depp.wang/2020/05/26/itranswarp-deploy-record/

### ISSUE THREAD

**Issue by DeppWang** [michaelliao/itranswarp#25]
https://depp.wang/2020/05/26/itranswarp-deploy-record/

**Comment by huanghe-1** [comment]
@DeppWang 你的这个博客是用itranswarp部署的吗？

**Comment by DeppWang** [comment]
不是的，是 hexo + next

**Comment by huanghe-1** [comment]
我也想做个博客，你觉得hexo + next合适，还是itranswarp合适？

**Comment by DeppWang** [comment]
如果你想写教程（类似 Python 教程），建议 itranswarp。如果只是想写博文，建议 hexo + next
