### ISSUE TITLE
IdUtil.java

### ISSUE THREAD

**Issue by lly835** [michaelliao/itranswarp#27]
为什么服务只能小于8台？
```
                if (n >= 0 && n < 8) {
                    logger.info("detect server id from host name {}: {}.", hostname, n);
                    return n;
                }
```

**Comment by michaelliao** [comment]
8台还不够？

**Comment by lly835** [comment]
不够呀，线上怎么可能才8台服务器


 原始邮件 
发件人: Michael Liao<notifications@github.com>
收件人: michaelliao/itranswarp<itranswarp@noreply.github.com>
抄送: lly835<lly835@163.com>; Author<author@noreply.github.com>
发送时间: 2020年7月15日(周三) 13:29
主题: Re: [michaelliao/itranswarp] IdUtil.java (#27)


8台还不够？

**Comment by michaelliao** [comment]
一台就能扛200万PV/天，你日访问量过亿了？

**Comment by lly835** [comment]
我是想直接在项目里用idUtil.java，很多个项目。




On 07/15/2020 20:04, Michael Liao wrote:

一台就能扛200万PV/天，你日访问量过亿了？

**Comment by jzhenxing** [comment]
如果留了5位的话其实是小于2^5=32吧？  所以小于32就行了。 个人感觉如果机器比较多但并发量不是特别高的话可以减少顺序号位数，增加机器码位数。

**Comment by ajiu-100wb** [comment]
> 8台还不够？

其实在这个问题上应该考虑如果机器很多情况如何优化
而不是纠结到底PV数量

**Comment by cnlinjie** [comment]
> 8台还不够？

是真的不够~
