### ISSUE TITLE
代码输入框有bug

### ISSUE THREAD

**Issue by suxder** [michaelliao/itranswarp#29]
在代码输入框中，按一下tab键，就会自动跳转出输入框。另外，代码输入框，输入代码后，如果代码是一个死循环语句，那么网页就会崩溃。

**Comment by michaelliao** [comment]
tab是切换输入框，浏览器行为

js代码在浏览器执行，死循环肯定会导致网页崩溃，不要写死循环

**Comment by suxder** [comment]
好的，明白了，谢谢廖老师
