### ISSUE TITLE
Python教程页面粘贴代码 格式不正确

### ISSUE THREAD

**Issue by gmbyys** [michaelliao/itranswarp#3]
首先非常感谢廖老师提供这样一个教程网站，本人一个小菜鸟在回复区域时使用遇到一个问题，觉得有必要改善，十分影响体验
个人问题为：
1 粘贴代码格式不正确
2 回复无法删除

以下为详细描述：
    我之前用过 Chrome 和Firefox，在粘贴Python代码时，编辑时看着代码都是正确的，但是发布后看着如图所示，我也选择了 是Python代码，但是如图，也不能删除 
https://www.liaoxuefeng.com/discuss/969955749132672/1289937167056930

![图片](https://user-images.githubusercontent.com/3353092/60378734-a30fcf80-9a59-11e9-86d5-65358af6c5b6.png)

**Comment by gmbyys** [comment]
另外 如果方便的话，麻烦回复一下我的问题，谢谢

**Comment by michaelliao** [comment]
这个html2md()写得不太完善，有空可以推一个pull request:

https://github.com/michaelliao/itranswarp/blob/master/src/main/resources/static/js/itranswarp.js#L345
