### ISSUE TITLE
IdUtil中shardId的最大值

### ISSUE THREAD

**Issue by hanhanhanxu** [michaelliao/itranswarp#38]
IdUtil中getServerIdAsLong()内限制了返回值只能是[0,8)，就是说shardId只能是占4个bit位，为什么[
分布式唯一ID生成器](https://www.liaoxuefeng.com/article/1280526512029729) 中却说是“5bit机器标识组成”？

**Comment by michaelliao** [comment]
5bit最多32台机器

**Comment by hanhanhanxu** [comment]
那不是应该限制getServerIdAsLong()返回[0,31)吗？
