### ISSUE TITLE
多个手机浏览器打开网页显示异常

### ISSUE THREAD

**Issue by nikissXI** [michaelliao/itranswarp#46]
廖雪峰网站所有页面都异常
前两周还正常，上周开始这样了，网站改动了什么吗
测试链接：https://www.liaoxuefeng.com/wiki/1252599548343744

![2HYFMD}ISECC QX~V@0$P8I](https://user-images.githubusercontent.com/31379266/175447446-46b1d46e-d9f6-4624-b145-a7942e65060f.jpg)

![7AJU9MWS6GQ68A`RSBLB6 V](https://user-images.githubusercontent.com/31379266/175447485-f63d9105-5cb7-4953-b471-91bec4ac33ce.jpg)

![0QVTW_05KO_1@LPT1G78 17](https://user-images.githubusercontent.com/31379266/175447495-ba00b926-42d9-426a-8859-00675aba9164.jpg)

**Comment by michaelliao** [comment]
手机系统 / 浏览器名字 / 地理位置 / 运营商 / 是否挂了代理？

直接访问CDN加速有无内容：

https://cdn.liaoxuefeng.com/static/css/bundle.css

**Comment by nikissXI** [comment]
我自己的是小米10s，安卓12，浏览器是via最新版本，我测试了小米自带浏览器没问题，kiwi浏览器也OK，但是群里其他人用他们的手机自带浏览器和夸克也是有问题的。任何运营商都一样，挂不挂代理都一样，因为都试过wifi，代理了，测试过跟这个没关系。
猜测是页面兼容性问题。
你给的那个CDN我用PC访问返回403.
![image](https://user-images.githubusercontent.com/31379266/175465106-06837a76-6f2e-4f1d-aa49-6b19a4e5291f.png)

**Comment by michaelliao** [comment]
你自己没问题就行。

**Comment by nikissXI** [comment]
> 你自己没问题就行。

????????????????
现在就是我的有问题啊

**Comment by michaelliao** [comment]
> 我测试了小米自带浏览器没问题，kiwi浏览器也OK

你不是说你的没问题吗？

同一个网络下是只有手机有问题还是电脑也有问题？国内还是国外？

**Comment by nikissXI** [comment]
> > 我测试了小米自带浏览器没问题，kiwi浏览器也OK
> 
> 你不是说你的没问题吗？
> 
> 同一个网络下是只有手机有问题还是电脑也有问题？国内还是国外？

不是哇，我上面不是说了出问题的是via浏览器，而且有其他群友测试了个别浏览器也不行
via浏览器通通不行，个别浏览器也不行
上个月用via浏览还正常的，这个月就这样了，期间没有进行任何系统升级和浏览器升级

**Comment by michaelliao** [comment]
手机系统浏览器没问题就没问题。

只有css/js的域名换了，因为jsdelivr被屏蔽了，upkg太慢，现在是aliyun的CDN
