### ISSUE TITLE
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

### ISSUE THREAD

**Issue by ckc** [michaelliao/itranswarp#49]
`ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)`

May I know if anyone experienced like this?
But good to enter this mysql db thru client app but failed the above in host CLI

**Comment by michaelliao** [comment]
Change localhost to 127.0.0.1 in application.yml if you run mysql in docker.
