### ISSUE TITLE
1.9版本的若干问题

### ISSUE THREAD

**Issue by polo2013** [michaelliao/itranswarp#50]
部署了1.9版本，发现几个问题
1、admin登录后，进入管理页面，发现头条没有新增的按钮
2、没有新增人员的入口，无法注册新人的话，是不是讨论区就没啥用了？
3、后台无法修改密码，包括admin，本想通过登录页的忘记口令来处理，无奈这个页面似乎不存在

一个建议：wiki里左半边的markdown编辑器似乎不支持表格语法，如果支持表格，就完美了。

**Comment by michaelliao** [comment]
1. 下一版加上
2. 集成一个第三方登录，不需要注册
3. 下一版加上

Markdown编辑器用的这个： https://getuikit.com/v2/docs/htmleditor.html
它不支持我也没办法，修改编辑器在我能力范围之外。
