### ISSUE TITLE
bundle.js太大，耗时30s

### ISSUE THREAD

**Issue by diedai** [michaelliao/itranswarp#51]
源码里的bundle.js，差不多3M，耗时30s。你官网的bundle.js，只有几百kb，耗时只有几十ms。

怎么压缩的？是用webpack吗？😄

**Comment by michaelliao** [comment]
Nginx开gzip压缩

**Comment by diedai** [comment]
> Nginx开gzip压缩

为了解决压缩问题还要专门安装NGINX吗？又不是分布式，也不需要负载均衡😅

有其他的方法吗？

**Comment by michaelliao** [comment]
放第三方站点再引用；
挂CDN；
用云厂商的ELB。

**Comment by diedai** [comment]
> Nginx开gzip压缩

谢谢老师。那我还是试下第一个方法：Nginx开gzip压缩^_^

**Comment by diedai** [comment]
> gzip

安装了nginx，并且开启gzip压缩之后，比之前快了很多，但还是需要耗时5s 😂

<img width="917" alt="image" src="https://user-images.githubusercontent.com/6100783/203814600-36759cda-8b2d-4e5e-9390-92d534a871fc.png">

**Comment by michaelliao** [comment]
你的网络不行，670k都是1秒内

把带宽提到10Mbps

**Comment by diedai** [comment]
> 你的网络不行，670k都是1秒内
> 
> 把带宽提到10Mbps

哈哈，我的是100M。访问你的官网正常，速度很快。其他网站也都很快。下载和抖音看4K世界杯都很快。
