### ISSUE TITLE
网站语言切换没有反应

### ISSUE THREAD

**Issue by ziyang-g** [michaelliao/itranswarp#58]
网站中英文切换没有反应，登录账号也没有反应

**Comment by michaelliao** [comment]
后台日志？前端控制台日志？

**Comment by ziyang-g** [comment]
Will
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "michaelliao/itranswarp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月31日(星期三) 晚上9:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [michaelliao/itranswarp] 网站语言切换没有反应 (Issue #58)





 
后台日志？前端控制台日志？

**Comment by ziyang-g** [comment]
仅有主页和退出有中英文切换是吗？我以为上面的标题也会进行切换。




Will
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "michaelliao/itranswarp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月31日(星期三) 晚上9:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [michaelliao/itranswarp] 网站语言切换没有反应 (Issue #58)





 
后台日志？前端控制台日志？
