### ISSUE TITLE
上传图片功能经常失效

### ISSUE THREAD

**Issue by diedai** [michaelliao/itranswarp#59]
创建文章的时候，上传图片功能经常突然失效，点击上传按钮没反应，重启浏览器或者电脑，一般可以解决，不行的话，多重启几次。

所有浏览器都有这个问题。

而且，上传图片功能失效的时候，浏览器下载图片功能也失效了。

控制台也没什么异常信息。

---
失效之后，随便写一个最简单的上传文件功能的html文件，然后都点击失效
<img width="1717" alt="image" src="https://github.com/michaelliao/itranswarp/assets/6100783/8dcf6eb0-89a4-458a-816a-3a112f2091e0">

**Comment by michaelliao** [comment]
你装的某个插件影响了页面正常功能。

**Comment by diedai** [comment]
> 你装的某个插件影响了页面正常功能。

其他浏览器都有这个问题，其他浏览器没有装任何插件，试了很多浏览器，都有这个问题。

**Comment by michaelliao** [comment]
你要区分是一个网站上传有问题还是所有网站上传都出问题，是不是中病毒了？
上传文件只是js代码，有问题console会报错

**Comment by diedai** [comment]
> 你要区分是一个网站上传有问题还是所有网站上传都出问题，是不是中病毒了？
> 上传文件只是js代码，有问题console会报错

出问题的时候，我单独写了一个最简单的独立的HTML上传文件功能测试也有问题，浏览器另存为图片也有问题。

正常的流程是：点击上传按钮，弹框选择图片文件，选择文件之后才会执行JS代码。现在的问题是，点击上传按钮没有任何反应，弹框都没出来，所以JS代码更没有执行，也没有console日志，因为JS都没执行。

**Comment by michaelliao** [comment]
你自己写的html有问题就不是项目的问题，浏览器刷新后就不应该与原来的页面关联。

**Comment by diedai** [comment]
> 

是项目的上传功能有问题，我才写了一个单独的html页面去测试一下😄
