### ISSUE TITLE
搜索功能-关键词文件明明包含关键词，但是分词的时候找不到关键词？

### ISSUE THREAD

**Issue by diedai** [michaelliao/itranswarp#64]
比如，查询关键词：线程。

关键词文件也包含：
![输入图片说明](https://foruda.gitee.com/images/1699782670197131104/64835e8e_94712.png "屏幕截图")

但是分词的时候，却找不到关键词：
![输入图片说明](https://foruda.gitee.com/images/1699782799461549677/80bf662c_94712.png "屏幕截图")

是什么原因呢？

**Comment by michaelliao** [comment]
redisearch的分词插件的问题，下个版本改成lunr
