### ISSUE TITLE
我自己实现了谷歌注册部分的代码 可以建个分支推送上去嘛

### ISSUE THREAD

**Issue by lazyboySun** [michaelliao/itranswarp#66]
现在会403 
![Uploading image.png…]()

**Comment by lazyboySun** [comment]
![image](https://github.com/michaelliao/itranswarp/assets/23733284/e58617f8-c674-4123-9858-f1eb4f36f61b)

**Comment by michaelliao** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
