### ISSUE TITLE
RediSearch创建多个索引之后，io.lettuce.core.api.sync.RedisHashCommands#hset写数据不能指定索引名字，导致搜索结果不准确

### ISSUE THREAD

**Issue by diedai** [michaelliao/itranswarp#67]
老师好！

# 问题
创建两个不同的索引，但是io.lettuce.core.api.sync.RedisHashCommands#hset写数据不能指定索引名字，导致搜索结果都是所有数据，而不是只搜索指定索引的数据。

---
举例
```java
commands.hset("doc:" + doc.id,  Map.of("type", doc.type, "name", doc.name, "content", doc.content, "publishAt", String.valueOf(doc.publishAt), "url", doc.url));
```

# 解决方法
创建索引，搜索数据，都是指定了索引名字。

但是写数据的时候，是没有指定索引名字的。

如果创建多个索引，想要只搜索指定索引名字的数据，写数据的时候怎么指定索引名字呢？

谢谢~

**Comment by michaelliao** [comment]
如果你需要一个完善的搜索引擎，建议还是用elastic search，优点是功能完备，单独维护，出了问题也不影响主系统，缺点是资源消耗大，云托管起步3节点太贵，维护麻烦。

如果是小型网站，干脆用静态索引，前端搜索，实时出结果。

目前正在改版，测试网站：https://gitsite.org/
