### ISSUE TITLE
登陆博客网站集成拓展

### ISSUE THREAD

**Issue by freemankevin** [michaelliao/itranswarp#68]
网址：https://www.liaoxuefeng.com/auth/signin

希望能集成，三者任意或者全部:
- Google 
- Apple
- Github

感谢大佬！

**Comment by michaelliao** [comment]
github是支持的，配置一下就行：

https://github.com/michaelliao/itranswarp/blob/master/src/main/java/com/itranswarp/oauth/provider/GithubOAuthProvider.java
