### ISSUE TITLE
IDE练习插件链接失效

### ISSUE THREAD

**Issue by oyjin** [michaelliao/itranswarp#8]
Java教程使用IDE练习插件一节中提供的插件链接已失效，添加插件时提示：An error occurred while collecting items to be installed

session context was:(profile=epp.package.java, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).

Artifact not found: https://liaoxuefeng.gitee.io/learn-java-update-site/plugins/com.itranswarp.learnjava.practice.plugin_1.0.1.jar.

https://liaoxuefeng.gitee.io/learn-java-update-site/plugins/com.itranswarp.learnjava.practice.plugin_1.0.1.jar

Artifact not found: https://liaoxuefeng.gitee.io/learn-java-update-site/features/java.practice.feature_1.0.1.jar.

https://liaoxuefeng.gitee.io/learn-java-update-site/features/java.practice.feature_1.0.1.jar

**Comment by michaelliao** [comment]
reload然后再试试

**Comment by oyjin** [comment]
衷心感谢廖老师回复，已经搞定了
