### ISSUE TITLE
pre块过长的时候整个页面会出现横向滚动条

### ISSUE THREAD

**Issue by imba-tjd** [michaelliao/itranswarp#9]
https://www.liaoxuefeng.com/wiki/1022910821149312/1023022043494624

![图片](https://user-images.githubusercontent.com/24759802/66447778-e549a380-ea81-11e9-9a52-7194e89b61b2.png)

是feature吗

另外想请问一下这种情况有方法找到是哪个元素引起的吗？我现在只会用肉眼看问题在哪

**Comment by michaelliao** [comment]
是feature
